/********************************************************************
* /seaquest/users/cmantill/DarkQuest/e1039-analysis/DataHits/src/SRawEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /seaquest/users/cmantill/DarkQuest/e1039-analysis/DataHits/src/SRawEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSRawEventDict();
extern void G__cpp_setup_inheritanceSRawEventDict();
extern void G__cpp_setup_typetableSRawEventDict();
extern void G__cpp_setup_memvarSRawEventDict();
extern void G__cpp_setup_globalSRawEventDict();
extern void G__cpp_setup_memfuncSRawEventDict();
extern void G__cpp_setup_funcSRawEventDict();
extern void G__set_cpp_environmentSRawEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/seaquest/users/cmantill/DarkQuest/e1039-analysis/DataHits/inc/SRawEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SRawEventDictLN_TClass;
extern G__linked_taginfo G__SRawEventDictLN_TBuffer;
extern G__linked_taginfo G__SRawEventDictLN_TMemberInspector;
extern G__linked_taginfo G__SRawEventDictLN_TObject;
extern G__linked_taginfo G__SRawEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SRawEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SRawEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SRawEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SRawEventDictLN_listlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SRawEventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__SRawEventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__SRawEventDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__SRawEventDictLN_TVector3;
extern G__linked_taginfo G__SRawEventDictLN_Hit;
extern G__linked_taginfo G__SRawEventDictLN_HitcLcLhitQuality;
extern G__linked_taginfo G__SRawEventDictLN_SRawEvent;
extern G__linked_taginfo G__SRawEventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__SRawEventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SRawEventDictLN_vectorlEHitcOallocatorlEHitgRsPgR;
extern G__linked_taginfo G__SRawEventDictLN_reverse_iteratorlEvectorlEHitcOallocatorlEHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SRawEventDictLN_pairlEintcOintgR;
extern G__linked_taginfo G__SRawEventDictLN_listlEpairlEintcOintgRcOallocatorlEpairlEintcOintgRsPgRsPgR;
extern G__linked_taginfo G__SRawEventDictLN_SRawEventcLcLTriggerType;
extern G__linked_taginfo G__SRawEventDictLN_SRawMCEvent;

/* STUB derived class for protected member access */
